POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Why Conspiracy theories are so appealing",
  "author": "hans jerasdfbsadf",
  "url": "fake.endpoint.com",
  "likes": 15
}